### ISSUE TITLE
Errors in your boiling points

### ISSUE THREAD

**Issue by ksaj** [sguessou/CL-gentle-intro#1]
The problem description itself is wrong, but your answers for boilingp in conditionals.lisp is wrong regardless if you interpreted it as was intended instead of how it is written.  

The assignment, as worded, is to return T if the temperature is *above boiling point*. You have answered T for if temp is *equal to boiling point* and returning NIL if it is *above boiling point* as was specified. 

If you answer the assignment as specified, temperatures *101 and greater* should return T. The author erroneously suggests that 100 should return NIL by requiring T for temperatures *above* boiling point instead of "at or above boiling point". 

You programmed "equals." He specified "greater than." He surely really meant "greater than or equal" since that's how boiling works. ;)

All these erroneous tutorials out there are a special beef of mine. Doesn't anyone check their work anymore?

**Comment by ksaj** [comment]
BTW,  here is another one:

[1]> (defun f-to-c (temp)
  (/ (* (- temp 32) 5) 9))
F-TO-C
[2]> (f-to-c 61)
145/9

Is that *really* a satisfactory answer?

**Comment by sguessou** [comment]
The usage of the "eq" function  is definitely wrong in this context... I've reworked the function to use the ">" operator instead. 
Btw one neat trick to force the result of "/" to be floating point number instead of ratio is to add "1.0" as extra argument. 
I think that the CLGITSC is a decent book for a complete LISP beginner. Seibel's book and Land of Lisp are next on my list ;)

**Comment by ksaj** [comment]
Excellent. You should also make it greater-than 99, since 100 is in fact boiling. That way you could make use of the function in a more true-to-life fashion. 

For the record, here is my (probably *still* less-than-optimal) code for the conversion. I took it a slight bit further to make it more sane:

```lisp
(format t "~d" (ceiling (+ (* 1.8 61) 32)))
```

Since the division is a constant, and you need the decimal to rid yourself of the /9 and /3 weirdness, I just use 1.8 to kill both birds with one stone.

Of course the number 61 would be a variable in a more usable context, but it is this way to keep it a one-liner for demonstration purposes. Feel free to improve on it. We're all learning here. 

edit: This is c-to-f btw. Thought I better mention that before the results throw you through a loop. But of course the reverse is a very similar function. Realized after I posted... Also, I'm going through Siebel's book now. Made me drop everything and pay more attention, heh. It is brilliant, and doesn't have the wonky flaws I keep finding in other books and tutorials. I still look at everyone else's code to learn from the real world. That's how I found your stuff. In reality, I probably should use ~1$ instad of ~d and ceiling, to get a single decimal place, but I wanted a simpler number and rounded up.

```lisp
(format t "~1$" (+ (* 1.8 61) 32))
```

is considerably nicer.

[Here](https://github.com/ksaj/clisp/blob/master/README.md) you can read my rant about crappy tutorials, complete with examples. I actually updated one of my examples as a result of this chat. So... thanks for being an accidental inspiration. ;)

**Comment by sguessou** [comment]
Thank you for your input and comments, that was really helpful! Btw, you should check some of the Lisp literature in offer on the [leanpub.com](https://leanpub.com/bookstore?search=lisp) platform, if you haven't already. I particularly enjoyed reading "Lisp Hackers", it's a short pdf containing interviews of Lisp hackers, Seibel's in there as well.
Take care and keep up the good work!

**Comment by ksaj** [comment]
I haven't, and I will. Thanks and happy Lisping!
